# -*- coding: utf-8 -*-
"""Analise HEAs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SWuTjAW29qzwQx30y56PGuFDgPJOzdjl
"""

import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

from sklearn.preprocessing import OrdinalEncoder  #transformar variaveis categoricas em numero
import warnings
warnings.filterwarnings('ignore')

# the libraries we need
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# pip install lazypredict
# !pip install pandas-profilling

# caminho google colab
# df = pd.read_csv('/content/drive/MyDrive/Documentos/TCC/HEAs_Machine_Learning/dados/dados_hea.csv', error_bad_lines=False, sep=';')

# caminho local
df = pd.read_csv('dados_hea.csv', error_bad_lines=False, sep=';')
# print(df.T)

#replace missing string values
data.ethernet_type.fillna('missing', inplace= True)
data.IP_protocol.fillna('missing', inplace= True)
data.TCP_flags.fillna('missing', inplace= True)

#replace missing values with 0
data.src_port.fillna(0, inplace= True)
data.dest_port.fillna(0, inplace= True)
data.time_to_live.fillna(0, inplace= True)
data.inter_arrival_time.fillna(0, inplace= True)
#print(data.head())

data["time_to_live"] = [float(str(i).replace(",", "")) for i in data["time_to_live"]]

data['time_to_live'] = data['time_to_live'].astype(float)

#Categorizando dados do tipo string